name: Deploy Resume to s3

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  deploy_resume:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Web Code
      uses: actions/checkout@v3

    - name: Deploy Resume to s3
      uses: dvelasquez/deploy-s3-action@main
      with:
        AWS_ACCESS_KEY_id: ${{secrets.AWS_ACCESS_KEY}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_KEY}}
        AWS_BUCKET_NAME: ${{secrets.WEBSITE_BUCKET_NAME}}
        DIST_LOCATION_CODE: ./webpage

    
    # - name: Deploy Resume to s3
    #   uses: shallwefootball/s3-upload-action@master
    #   with:
    #     aws_key_id: ${{secrets.AWS_ACCESS_KEY}}
    #     aws_secret_access_key: ${{secrets.AWS_SECRET_KEY}}
    #     aws_bucket: ${{secrets.WEBSITE_BUCKET_NAME}}
    #     source_dir: webpage

    # - name: Configure AWS Credentials
    #   uses: aws-actions/configure-aws-credentials@v1.6.1
    #   with:
    #     aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}}
    #     aws-secret-access-key: ${{secrets.AWS_SECRET_KEY}}
    #     aws-region: us-west-2

    