name: Deploy Resume Website to Test

on:

  workflow_dispatch:

jobs:
  deploy_resume:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Web Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1.6.1
      with:
        aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}}
        aws-secret-access-key: ${{secrets.AWS_SECRET_KEY}}
        aws-region: us-west-2

    - name: Deploy Resume files to s3
      run: aws s3 sync webpage s3://${{secrets.WEBSITE_BUCKET_NAME_TEST}} --delete
    